
# Common Conventions and API Elements of scikit-learn

Notebook ini merangkum Chapter 1 dan menjelaskan konsep dasar API scikit-learn, termasuk estimator, transformer, pipeline, hyperparameter tuning, metadata, dan best practice penggunaan library.



## Tujuan Pembelajaran

Setelah mempelajari notebook ini, pembaca diharapkan mampu:

- Memahami filosofi desain scikit-learn.
- Memahami konsep estimator dan transformer.
- Menggunakan `fit()`, `predict()`, `transform()`, dan `fit_transform()`.
- Membuat custom estimator sederhana.
- Memahami pipeline dan workflow automation.
- Mengenal hyperparameter tuning.
- Memahami metadata dan API scikit-learn.


In [1]:

import numpy as np
import pandas as pd

from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier



## Ringkasan Chapter

Scikit-learn dirancang berdasarkan prinsip **consistency**, **simplicity**, **modularity**, dan **reusability**. Hampir seluruh algoritma machine learning di dalam library ini menggunakan pola API yang sama sehingga lebih mudah dipelajari dan digunakan.

Konsep utama chapter ini adalah bahwa hampir semua model mengikuti alur:

1. Membuat objek model.
2. Melatih model dengan `fit()`.
3. Menghasilkan prediksi dengan `predict()` atau melakukan transformasi dengan `transform()`.
4. Mengevaluasi hasil menggunakan metode seperti `score()`.



## Filosofi Desain scikit-learn

Scikit-learn memiliki desain yang konsisten di seluruh algoritma. Baik menggunakan Linear Regression, Random Forest, KNN, maupun model lain, pola penggunaannya hampir sama.

| Prinsip | Penjelasan |
|----------|------------|
| Consistency | Semua model menggunakan API yang seragam |
| Simplicity | Mudah dipelajari dan digunakan |
| Modularity | Komponen dapat digabungkan |
| Reusability | Pipeline dan transformer dapat digunakan ulang |



## Memahami Estimator

Estimator adalah objek yang belajar dari data. Hampir semua algoritma machine learning dalam scikit-learn merupakan estimator.

Estimator biasanya memiliki dua metode utama:

- `fit()` → belajar dari data
- `predict()` → menghasilkan prediksi


In [2]:

X = np.array([[1],[2],[3],[4],[5]])
y = np.array([1,2,3,3.5,5])

model = LinearRegression()
model.fit(X,y)

prediksi = model.predict([[6],[7]])

print(prediksi)


[5.75 6.7 ]



### Alur Kerja Estimator

| Tahap | Fungsi |
|---------|---------|
| Membuat model | `LinearRegression()` |
| Training | `fit(X,y)` |
| Prediksi | `predict(X_baru)` |
| Evaluasi | `score(X,y)` |



## Fit, Predict, dan Fit Predict

Pada supervised learning, data training digunakan untuk proses `fit()`, sedangkan data baru digunakan pada `predict()`.

Pada beberapa algoritma unsupervised seperti K-Means tersedia shortcut berupa `fit_predict()`, yaitu melakukan training dan menghasilkan label cluster sekaligus.


In [3]:

from sklearn.cluster import KMeans

X = np.array([[1],[2],[3],[4],[5]])

kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
labels = kmeans.fit_predict(X)

print(labels)


[0 0 0 1 1]



## Transformer dan Method Transform

Transformer digunakan untuk mengubah data sebelum masuk ke model.

Contoh transformasi:

- Scaling
- Normalisasi
- Encoding
- Feature Engineering

Transformer memiliki dua metode utama:

- `fit()` → mempelajari parameter transformasi
- `transform()` → menerapkan transformasi


In [4]:

X = np.array([[1,2],
              [3,4],
              [5,6]])

scaler = StandardScaler()

scaler.fit(X)

X_scaled = scaler.transform(X)

print(X_scaled)


[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]



### Perbedaan fit() dan transform()

| Method | Fungsi |
|----------|---------|
| fit() | Menghitung parameter dari data |
| transform() | Mengubah data menggunakan parameter tadi |
| fit_transform() | Menggabungkan fit dan transform |


In [5]:

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled)


[[-1.22474487 -1.22474487]
 [ 0.          0.        ]
 [ 1.22474487  1.22474487]]



## Mengapa Transformasi Penting?

Banyak algoritma machine learning sensitif terhadap skala data.

Contoh algoritma yang sangat terbantu dengan scaling:

- KNN
- Logistic Regression
- SVM
- Neural Network

Transformasi juga membantu mengurangi pengaruh perbedaan satuan antar fitur.



## Custom Estimator dan Custom Transformer

Salah satu keunggulan scikit-learn adalah kemudahan membuat estimator sendiri.

Custom estimator harus mengikuti API yang sama sehingga tetap kompatibel dengan:

- Pipeline
- GridSearchCV
- Cross Validation


In [6]:

from sklearn.base import BaseEstimator, TransformerMixin

class AddOneTransformer(BaseEstimator, TransformerMixin):

    def fit(self, X, y=None):
        return self

    def transform(self, X):
        return X + 1

X = np.array([[1],[2],[3]])

custom = AddOneTransformer()

print(custom.fit_transform(X))


[[2]
 [3]
 [4]]



## Pipeline dan Workflow Automation

Pipeline memungkinkan beberapa langkah preprocessing dan modeling digabung menjadi satu workflow.

Keuntungan pipeline:

- Mengurangi kesalahan preprocessing
- Meningkatkan reproducibility
- Memudahkan deployment
- Mendukung cross-validation dan grid search



### Struktur Pipeline

```text
Data
 ↓
Transformer
 ↓
Transformer
 ↓
Model
 ↓
Prediksi
```


In [7]:

from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

data = load_breast_cancer()

X_train, X_test, y_train, y_test = train_test_split(
    data.data,
    data.target,
    random_state=42
)

pipe = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=5000))
])

pipe.fit(X_train, y_train)

print("Accuracy:", pipe.score(X_test, y_test))


Accuracy: 0.9790209790209791



## MLOps dan Pipeline

Chapter ini juga memperkenalkan konsep MLOps secara singkat.

MLOps bertujuan mengotomatisasi siklus hidup machine learning mulai dari:

1. Training
2. Validation
3. Deployment
4. Monitoring
5. Retraining

Pipeline merupakan salah satu fondasi penting dalam implementasi MLOps modern.



## Common Attributes dan Methods

Sebagian besar model scikit-learn memiliki atribut dan method yang seragam.

| Atribut / Method | Fungsi |
|------------------|---------|
| coef_ | Koefisien model |
| intercept_ | Nilai intercept |
| predict() | Prediksi |
| score() | Evaluasi model |
| get_params() | Melihat parameter |
| set_params() | Mengubah parameter |


In [8]:

model = LinearRegression()

model.fit(X, np.array([1,2,3]))

print("Coef :", model.coef_)
print("Intercept :", model.intercept_)
print("Score :", model.score(X, np.array([1,2,3])))


Coef : [1.]
Intercept : 4.440892098500626e-16
Score : 1.0



## Hyperparameter Tuning

Hyperparameter adalah parameter yang ditentukan sebelum model dilatih.

Contoh:

| Model | Hyperparameter |
|---------|---------------|
| Random Forest | n_estimators |
| KNN | n_neighbors |
| SVM | C, gamma |
| Decision Tree | max_depth |


In [9]:

model = RandomForestClassifier(
    n_estimators=100,
    max_depth=5,
    random_state=42
)

print(model.get_params()["n_estimators"])
print(model.get_params()["max_depth"])


100
5



## Grid Search

Grid Search digunakan untuk mencari kombinasi hyperparameter terbaik secara otomatis.


In [10]:

from sklearn.datasets import load_iris

iris = load_iris()

param_grid = {
    "n_estimators":[50,100],
    "max_depth":[3,5,None]
}

grid = GridSearchCV(
    RandomForestClassifier(random_state=42),
    param_grid,
    cv=3
)

grid.fit(iris.data, iris.target)

print("Best Params:", grid.best_params_)
print("Best Score :", grid.best_score_)


Best Params: {'max_depth': 3, 'n_estimators': 50}
Best Score : 0.9666666666666667



## Metadata dan Tags

Scikit-learn menggunakan metadata untuk mengontrol perilaku estimator dalam berbagai kondisi.

Metadata dapat menyimpan informasi seperti:

- Jenis input yang didukung
- Kemampuan menangani missing values
- Dukungan multi-output
- Routing informasi tambahan dalam pipeline

Konsep ini menjadi semakin penting pada workflow machine learning yang kompleks.



## Best Practices Penggunaan API

Beberapa praktik terbaik yang direkomendasikan:

| Praktik | Alasan |
|----------|---------|
| Gunakan Pipeline | Mengurangi data leakage |
| Lakukan preprocessing dengan transformer | Konsisten |
| Gunakan cross-validation | Evaluasi lebih stabil |
| Gunakan GridSearchCV | Optimasi parameter |
| Pisahkan train dan test set | Generalisasi model |
| Gunakan API standar scikit-learn | Kode lebih mudah dipelihara |



## Ringkasan Konsep Penting

| Konsep | Fungsi Utama |
|----------|-------------|
| Estimator | Belajar dari data |
| Transformer | Mengubah data |
| fit() | Melatih model |
| predict() | Prediksi |
| transform() | Transformasi data |
| fit_transform() | Fit + Transform |
| Pipeline | Otomatisasi workflow |
| GridSearchCV | Hyperparameter tuning |
| Metadata | Informasi tambahan model |



## Kesimpulan Chapter

Chapter ini memperkenalkan fondasi utama scikit-learn dan pola API yang digunakan hampir di seluruh library.

Poin terpenting yang perlu dipahami:

- Semua estimator menggunakan API yang konsisten.
- `fit()`, `predict()`, dan `transform()` merupakan inti penggunaan scikit-learn.
- Transformer digunakan untuk preprocessing data.
- Pipeline membantu mengotomatisasi workflow machine learning.
- Hyperparameter tuning dapat dilakukan menggunakan GridSearchCV.
- Custom estimator dapat dibuat selama mengikuti API scikit-learn.
- Konsistensi API menjadi alasan utama mengapa scikit-learn sangat populer dalam pembelajaran dan pengembangan machine learning.
